export const data = [
    {
      id: "001",
      name: "商品1",
      price: 10,
      quantity: 5,
      category: "类别1",
      brand: "品牌1",
      color: "红色",
      size: "S",
      weight: "1kg",
      description: "这是商品1的描述",
    },
    {
      id: "002",
      name: "商品2",
      price: 20,
      quantity: 3,
      category: "类别2",
      brand: "品牌2",
      color: "蓝色",
      size: "M",
      weight: "1kg",
      description: "这是商品2的描述",
    },
    {
      id: "003",
      name: "商品3",
      price: 30,
      quantity: 8,
      category: "类别1",
      brand: "品牌1",
      color: "绿色",
      size: "L",
      weight: "1kg",
      description: "这是商品3的描述",
    },
    {
      id: "004",
      name: "商品4",
      price: 15,
      quantity: 10,
      category: "类别2",
      brand: "品牌3",
      color: "黄色",
      size: "XL",
      weight: "1kg",
      description: "这是商品4的描述",
    },
    {
      id: "005",
      name: "商品5",
      price: 25,
      quantity: 2,
      category: "类别3",
      brand: "品牌2",
      color: "紫色",
      size: "M",
      weight: "1kg",
      description: "这是商品5的描述",
    },
    {
      id: "006",
      name: "商品6",
      price: 12,
      quantity: 7,
      category: "类别1",
      brand: "品牌3",
      color: "橙色",
      size: "L",
      weight: "1kg",
      description: "这是商品6的描述",
    },
    {
      id: "007",
      name: "商品7",
      price: 18,
      quantity: 4,
      category: "类别2",
      brand: "品牌1",
      color: "红色",
      size: "S",
      weight: "1kg",
      description: "这是商品7的描述",
    },
    {
      id: "008",
      name: "商品8",
      price: 22,
      quantity: 9,
      category: "类别3",
      brand: "品牌3",
      color: "蓝色",
      size: "M",
      weight: "1kg",
      description: "这是商品8的描述",
    },
    {
      id: "009",
      name: "商品9",
      price: 28,
      quantity: 6,
      category: "类别1",
      brand: "品牌2",
      color: "绿色",
      size: "XL",
      weight: "1kg",
      description: "这是商品9的描述",
    },
    {
      id: "010",
      name: "商品10",
      price: 14,
      quantity: 3,
      category: "类别2",
      brand: "品牌1",
      color: "橙色",
      size: "S",
      weight: "1kg",
      description: "这是商品10的描述",
    },
    {
      id: "011",
      name: "商品11",
      price: 17,
      quantity: 5,
      category: "类别3",
      brand: "品牌2",
      color: "紫色",
      size: "L",
      weight: "1kg",
      description: "这是商品11的描述",
    },
    {
      id: "012",
      name: "商品12",
      price: 21,
      quantity: 8,
      category: "类别1",
      brand: "品牌3",
      color: "红色",
      size: "M",
      weight: "1kg",
      description: "这是商品12的描述",
    },
    {
      id: "013",
      name: "商品13",
      price: 27,
      quantity: 4,
      category: "类别2",
      brand: "品牌1",
      color: "蓝色",
      size: "XL",
      weight: "1kg",
      description: "这是商品13的描述",
    },
    {
      id: "014",
      name: "商品14",
      price: 13,
      quantity: 6,
      category: "类别1",
      brand: "品牌2",
      color: "绿色",
      size: "S",
      weight: "1kg",
      description: "这是商品14的描述",
    },
    {
      id: "015",
      name: "商品15",
      price: 16,
      quantity: 2,
      category: "类别3",
      brand: "品牌3",
      color: "紫色",
      size: "M",
      weight: "1kg",
      description: "这是商品15的描述",
    },
  ];